* Delaying Releases
** About
   - Helpful in taking control of a release due to various known or unknown setbacks
   - Releases can be delayed to a later date before intended release date or they can be delayed until the next scheduled release (merge the release).
   - Releases can be delayed indefinitely until a manual user action is taken.
   - Should ideally only be used in significant moments of the release cycle, when no alternatives are present.
** Usefulness
   - If the staged rollout of the current release has not finished before the intended rollout date, the next release can be delayed appropriately.
   - If the release has bugs that need to be corrected, and something absolutely must go out, the release can be delayed
     - This should only be used when kicking the feature out of the release is not an option.
** Downsides
   - Can cause major indeterminism in the scheduling of the [[./trains.org][release train]].
   - Increases lead times on bug fixes, features, config changes, pretty much everything.
** Potential mechanics
   - A [[./trains.org][train]], can be automatically delayed by the following events:
     - The next train is about to set off (next release cycle), but the previous one has *not*:
       - Had hotfixes merged back to mainline.
       - Completed its staged rollout fully (optional).
   - A train, can be manually paused (indefinite delay) and the subsequent trains are paused as a result until manually unpaused.
